### ISSUE TITLE
See also still link to gitlab repo

### ISSUE THREAD

**Issue by nick-wang** [SUSE/sapwmp#1]
After migrate to the github, the "See also" chapter still point to gitlab. The content branch seems not used anymore, 
@Werkov Do you agree to remove this part?

```
## See also

This is based on modifying SAP profile. For the rejected and unmaintained
variant see the branch

  * [PAM based](https://gitlab.suse.de/mkoutny/wmp-repo/tree/pam-rpm) (non-public).
```

**Comment by Werkov** [comment]
Yes, the branch is not used and it's also only kept on internal Gitlab. I kept this paragraph on purpose for archive reasons (if it showed useful sometime in the future).

**Comment by nick-wang** [comment]
Close due to https://github.com/SUSE/sapwmp/pull/3 merged.
