### ISSUE TITLE
Remove "is_opensuse" macro

### ISSUE THREAD

**Issue by nick-wang** [SUSE/sapwmp#2]
"is_opensuse" is obsolete in SLE by "suse_version" and "sle_version". 
Actually after move to Github, no longer need the conditions for the URL to the version specific susedoc, could link to [github repo](https://github.com/SUSE/sapwmp)

**Comment by Werkov** [comment]
Ad obsolescence, I followed the [table on openSUSE wiki](https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Detect_a_distribution_flavor_for_special_code). I admit, I don't know what are the latest recommendations. If you find them, feel free to modify the macros accordingly.

Ad `URL:`, I don't know whether it's suited for a developer link or package user link. As I looked around at some packages, it seemed to me to be rather for the users. If you wish to change this field, make sure that README visibly points to the user docs. (Personally, I'd stick to the current form though.)

**Comment by nick-wang** [comment]
> Ad `URL:`, I don't know whether it's suited for a developer link or package user link. As I looked around at some packages, it seemed to me to be rather for the users. If you wish to change this field, make sure that README visibly points to the user docs. (Personally, I'd stick to the current form though.)

doc/home page is more common i think. However, i think the README is even more detailed than the original link. I think it is good to point to an unified SUSE doc, not version specific links with actually little trivials differences.

**Comment by Werkov** [comment]
The README should be more detailed only [temporarily](https://gitlab.suse.de/mkoutny/wmp-repo/-/issues/2#note_269267). I expect users to start with our documentation and install the RPM as the consequence and not vice versa. I.e. this link shouldn't be that much important, however, if they run into the URL, it'd point them back to the official documentation (instead of the developer-oriented readme).

**Comment by nick-wang** [comment]
Official documentation is better indeed, should aligned to it as long as it exist. 
I just hoped it is not version specific, since actually not much differences found in the doc atm.

I will only replace the "is_opensuse" macro and leave the URL conditions

**Comment by nick-wang** [comment]
Close due to https://github.com/SUSE/sapwmp/pull/3 merged.
