### ISSUE TITLE
sapwmp should include a script to check correct setup

### ISSUE THREAD

**Issue by ricardobranco777** [SUSE/sapwmp#4]
Something like:

https://github.com/scmschmidt/wmp_check/

**Comment by nick-wang** [comment]
It is good to have something to do a preflight check. Sounds like the project you refered is good for this.

@scmschmidt Would you like to include your [wmp_check](https://github.com/scmschmidt/wmp_check/) here as a starting point for the development of preflight check and add things based on it? Or leave it to for your case and start with new design/code. 
How do you think of it?

**Comment by scmschmidt** [comment]
@nick-wang Yes, we can include it, but I haven't tested it thoroughly yet. What is needed to be done?

**Comment by nick-wang** [comment]
@scmschmidt Not necessary to be prefect. We can use this as start point, then make it robust and add more features.
I will try to use and devel on it first with your permission (Though you licensed it in GPLv3 already, lol).
Not necessary to redesign or use other language/structure unless we need.
